version: "3.8"
services:
  app: # => サービス名は任意
    build: ./infra/php # docker buildを実行する際の現在の作業ディレクトリ
    volumes:
      #ホスト側の ./backend ディレクトリをappサービスのコンテナ内 /work へマウント
      - ./backend:/work

  # 追記
  web:
    #コンテナを起動させるnginxイメージを指定します。
    image: nginx:1.18-alpine
    #nginxへ外(ホスト側)からコンテナ内へアクセスさせるため公開用のポートを設定します。
    #ホスト側:コンテナ側 と設定します。
    ports:
      - 10080:80
    #ホスト側にあるディレクトリ、ファイルをコンテナ内へマウントさせています。
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
